随机分组：
1. 3-4人一组
2. 男女均衡分配

In [1]:
import pandas as pd
from pprint import pprint

In [15]:
path = '课程考核记录/2026春/students_hometown_2026.csv'
stud_pd = pd.read_csv(path)
num_stud = len(stud_pd)
print(num_stud)
stud_pd.head(2)

23

    姓名 性别 家乡所在省 家乡所在市    家乡经度   家乡纬度
0  杨茗涵  女   云南省   昆明市  102.76  25.04
1  曾紫芯  女   湖南省   湘潭市  112.94  27.83

In [14]:
stud_pd_ = stud_pd.sample(frac=1).reset_index(drop=True) 
stud_pd_.head(2)

    姓名 性别    家乡所在省 家乡所在市    家乡经度   家乡纬度
0  李伟峰  男      云南省   昆明市  102.76  25.04
1  廖炜婕  女  广西壮族自治区   贺州市  111.34  24.24

In [4]:
stud_special = stud_pd_[stud_pd_['姓名']=='李月']
stud_pd_ = stud_pd_.drop(stud_special.index)
stud_special
# stud_pd_

   姓名 性别 家乡所在省 家乡所在市    家乡经度   家乡纬度
7  李月  女   云南省   昭通市  103.71  27.33

In [5]:
num_groups = len(stud_pd_) // 3  ## 整除
num_groups

7

In [6]:
stud_boys = stud_pd_[stud_pd_['性别'] == '男']
stud_girls = stud_pd_[stud_pd_['性别'] == '女']
# print(len(stud_boys))
# print(len(stud_girls))

In [7]:
## 初始化各组学生列表
stud_groups = []
for i in range(num_groups):
    stud_groups.append([])
stud_groups

[[], [], [], [], [], [], []]

In [12]:
i = 0
for boy in stud_boys['姓名']:
    # print(boy)
    stud_groups[i].append(boy)
    i = i+1
    if i>=num_groups: 
        i = 0
# print(i)

for girl in stud_girls['姓名']:
    # print(girl)
    stud_groups[i].append(girl)
    i = i+1
    if i>=num_groups: 
        i = 0

for stud in stud_special['姓名']:
    stud_groups[i].append(stud)
    i = i+1
    if i>=num_groups: 
        i = 0

In [13]:
# pprint(stud_groups)